name: barcode_validator
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - bioconda::blast
  - bioconda::hmmer
  - conda-forge::pip
  - pip:
    - pyyaml
    - pandas==1.5.3
    - biopython==1.84
    - requests
    - ete3
    - openpyxl==3.1.2
    - xlrd==2.0.1
    - numpy==1.23.5
    - nbitk
