name: barcode_validator
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - requests
  - gspread
  - oauth2client
  - pyyaml
  - pandas
  - hmmer
  - pip
  - pip:
    - subprocess.run
    - boldigger2
