name: barcode_validator
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython
  - ete3
  - blast
  - requests
  - pyyaml
  - pandas
  - hmmer
  - openpyxl
  - xlrd=1.1.0
  - pip
  - pip:
    - subprocess.run
    - git+ssh://git@gitlab.com/naturalis/bii/bioinformatics/nbt.git
