# Alignment configuration. This needs the location of an HMM file for the focal marker.
hmm_file: ./COI-5P.hmm

# Persistence location, if any. The current implementation persists the results to a google spreadsheet. This can
# be extended to make it so that the results, instead, go to something like the iBOL Europe web app's database,
# or to Naturalis's core sequence cloud.
persist: gspread
gspread: https://docs.google.com/spreadsheets/d/1xJJKLAgDFvPxRnoTPfmDmTsZkq5o6i5fsQvOydMd068/
credentials_file: ../../examples/credentials.json

# Configuration of the ID checking service. At present this is limited to boldigger2, which additionally requires
# a username and password.
# idcheck: boldigger2
idcheck: blast
level: family
email: bioinformatics@naturalis.nl

# Configuration for logging. The verbosity level specified here is overridden by the value provided on the command
# line with the -v/-verbosity argument. The log file is written to the current working directory.
log_level: INFO
log_file: ./log_file.log

# Which translation table is used. This value is an integer that corresponds to the tables used by NCBI and parsed
# by biopython. The default is 5, which is the table for invertebrate mitochondrial DNA.
# See https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG5
translation_table: 5

# Minimum length within the barcode region.
min_seq_length: 500