# Alignment configuration. This needs the location of an HMM file for the focal marker.
hmm_file: ../examples/COI-5P.hmm

# Which taxonomic level to use for the ID check.
level: family

# Where to constrain the BLAST search. This indicates the higher taxon level to which the expected taxon belongs and
# to which the search should be constrained. This is used to speed up the search and to avoid false positives.
constrain: class

# Configuration for local blast. This is used when the idcheck is set to localblast.
blast_db: /home/rutger.vos/data/ncbi/nt/nt
num_threads: 24 # MaaS 37
evalue: 1e-5
max_target_seqs: 10
word_size: 28
BLASTDB_LMDB_MAP_SIZE: 180000000000 # MaaS 37, 180GB
BLASTDB: /home/rutger.vos/data/ncbi/nt

# Location of the NCBI taxonomy dump. This must be the tar file that contains the nodes.dmp and names.dmp files.
# http://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
ncbi_taxonomy: /home/rutger.vos/data/ncbi/taxdump/taxdump.tar.gz

# Configuration for logging. The verbosity level specified here is overridden by the value provided on the command
# line with the -v/-verbosity argument. The log file is written to the current working directory.
log_level: INFO
log_file: ../log_file.log

# Which translation table is used. This value is an integer that corresponds to the tables used by NCBI and parsed
# by biopython. The default is 5, which is the table for invertebrate mitochondrial DNA.
# See https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG5
translation_table: 5

# Minimum length within the barcode region.
min_seq_length: 500
